// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/eezy-tech/one-stocks/server/internal/shared/usertype"
	"github.com/google/uuid"
)

type Generation struct {
	ID          uuid.UUID
	UserID      string
	Filename    string
	PreviewKey  *string
	Title       string
	Description string
	Keywords    []string
	Category    *string
	Provider    *string
	Model       *string
	CreatedAt   time.Time
	PlatformID  *string
}

type Profile struct {
	UserID     string
	FirstName  *string
	LastName   *string
	Email      *string
	ProfileUrl *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserType   usertype.Type
}

type UserSetting struct {
	UserID            string
	KeywordsPerImage  int32
	TitleStyle        string
	BlockedTerms      string
	OutputLanguages   string
	UpdatedAt         time.Time
	CreatedAt         time.Time
	SelectedPlatforms string
}
