// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countGenerations = `-- name: CountGenerations :one
select count(*) from generations where user_id = $1
`

func (q *Queries) CountGenerations(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countGenerations, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGeneration = `-- name: DeleteGeneration :execrows
delete from generations where id = $1 and user_id = $2
`

type DeleteGenerationParams struct {
	ID     uuid.UUID
	UserID string
}

// ต้องเช็ค user_id ด้วย ไม่งั้นใครรู้ id ก็ลบของคนอื่นได้
func (q *Queries) DeleteGeneration(ctx context.Context, arg DeleteGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGeneration, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserSettings = `-- name: GetUserSettings :one
select keywords_per_image, title_style, blocked_terms, output_languages
from user_settings
where user_id = $1
`

type GetUserSettingsRow struct {
	KeywordsPerImage int32
	TitleStyle       string
	BlockedTerms     string
	OutputLanguages  string
}

func (q *Queries) GetUserSettings(ctx context.Context, userID string) (GetUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i GetUserSettingsRow
	err := row.Scan(
		&i.KeywordsPerImage,
		&i.TitleStyle,
		&i.BlockedTerms,
		&i.OutputLanguages,
	)
	return i, err
}

const insertGeneration = `-- name: InsertGeneration :one
insert into generations (
  user_id, filename, preview_key, title, description,
  keywords, category, provider, model
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, filename, preview_key, title, description,
          keywords, category, provider, model, created_at
`

type InsertGenerationParams struct {
	UserID      string
	Filename    string
	PreviewKey  *string
	Title       string
	Description string
	Keywords    []string
	Category    *string
	Provider    *string
	Model       *string
}

type InsertGenerationRow struct {
	ID          uuid.UUID
	Filename    string
	PreviewKey  *string
	Title       string
	Description string
	Keywords    []string
	Category    *string
	Provider    *string
	Model       *string
	CreatedAt   time.Time
}

func (q *Queries) InsertGeneration(ctx context.Context, arg InsertGenerationParams) (InsertGenerationRow, error) {
	row := q.db.QueryRow(ctx, insertGeneration,
		arg.UserID,
		arg.Filename,
		arg.PreviewKey,
		arg.Title,
		arg.Description,
		arg.Keywords,
		arg.Category,
		arg.Provider,
		arg.Model,
	)
	var i InsertGenerationRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.PreviewKey,
		&i.Title,
		&i.Description,
		&i.Keywords,
		&i.Category,
		&i.Provider,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const listGenerations = `-- name: ListGenerations :many
select id, filename, preview_key, title, description,
       keywords, category, provider, model, created_at
from generations
where user_id = $1
order by created_at desc
limit $2 offset $3
`

type ListGenerationsParams struct {
	UserID string
	Limit  int32
	Offset int32
}

type ListGenerationsRow struct {
	ID          uuid.UUID
	Filename    string
	PreviewKey  *string
	Title       string
	Description string
	Keywords    []string
	Category    *string
	Provider    *string
	Model       *string
	CreatedAt   time.Time
}

// ใหม่ไปเก่า ใช้ดัชนี generations_user_created_idx ตอบได้ทั้งกรองและเรียง
func (q *Queries) ListGenerations(ctx context.Context, arg ListGenerationsParams) ([]ListGenerationsRow, error) {
	rows, err := q.db.Query(ctx, listGenerations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenerationsRow
	for rows.Next() {
		var i ListGenerationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.PreviewKey,
			&i.Title,
			&i.Description,
			&i.Keywords,
			&i.Category,
			&i.Provider,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProfile = `-- name: UpsertProfile :one
insert into profiles (user_id, first_name, last_name, email, profile_url)
values ($1, $2, $3, $4, $5)
on conflict (user_id) do update set
  first_name  = excluded.first_name,
  last_name   = excluded.last_name,
  email       = excluded.email,
  profile_url = excluded.profile_url,
  updated_at  = now()
returning user_id, first_name, last_name, email, profile_url
`

type UpsertProfileParams struct {
	UserID     string
	FirstName  *string
	LastName   *string
	Email      *string
	ProfileUrl *string
}

type UpsertProfileRow struct {
	UserID     string
	FirstName  *string
	LastName   *string
	Email      *string
	ProfileUrl *string
}

// คัดลอกข้อมูลผู้ใช้จาก Clerk มาเก็บไว้ฝั่งเรา
// เพื่อให้ join กับตารางอื่นได้โดยไม่ต้องยิงไปถาม Clerk ทุกครั้ง
func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UpsertProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ProfileUrl,
	)
	var i UpsertProfileRow
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.ProfileUrl,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :one
insert into user_settings (
  user_id, keywords_per_image, title_style, blocked_terms, output_languages
) values ($1, $2, $3, $4, $5)
on conflict (user_id) do update set
  keywords_per_image = excluded.keywords_per_image,
  title_style        = excluded.title_style,
  blocked_terms      = excluded.blocked_terms,
  output_languages   = excluded.output_languages,
  updated_at         = now()
returning keywords_per_image, title_style, blocked_terms, output_languages
`

type UpsertUserSettingsParams struct {
	UserID           string
	KeywordsPerImage int32
	TitleStyle       string
	BlockedTerms     string
	OutputLanguages  string
}

type UpsertUserSettingsRow struct {
	KeywordsPerImage int32
	TitleStyle       string
	BlockedTerms     string
	OutputLanguages  string
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) (UpsertUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertUserSettings,
		arg.UserID,
		arg.KeywordsPerImage,
		arg.TitleStyle,
		arg.BlockedTerms,
		arg.OutputLanguages,
	)
	var i UpsertUserSettingsRow
	err := row.Scan(
		&i.KeywordsPerImage,
		&i.TitleStyle,
		&i.BlockedTerms,
		&i.OutputLanguages,
	)
	return i, err
}
