// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"time"

	"github.com/eezy-tech/one-stocks/server/internal/shared/usertype"
	"github.com/google/uuid"
)

const countGenerations = `-- name: CountGenerations :one
select count(*) from generations where user_id = $1
`

func (q *Queries) CountGenerations(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countGenerations, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGenerationsByPlatform = `-- name: CountGenerationsByPlatform :one
select count(*) from generations where user_id = $1 and platform_id = $2
`

type CountGenerationsByPlatformParams struct {
	UserID     string
	PlatformID *string
}

func (q *Queries) CountGenerationsByPlatform(ctx context.Context, arg CountGenerationsByPlatformParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGenerationsByPlatform, arg.UserID, arg.PlatformID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGeneration = `-- name: DeleteGeneration :execrows
delete from generations where id = $1 and user_id = $2
`

type DeleteGenerationParams struct {
	ID     uuid.UUID
	UserID string
}

// ต้องเช็ค user_id ด้วย ไม่งั้นใครรู้ id ก็ลบของคนอื่นได้
func (q *Queries) DeleteGeneration(ctx context.Context, arg DeleteGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGeneration, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserSettings = `-- name: GetUserSettings :one
select keywords_per_image, title_style, blocked_terms, output_languages, selected_platforms
from user_settings
where user_id = $1
`

type GetUserSettingsRow struct {
	KeywordsPerImage  int32
	TitleStyle        string
	BlockedTerms      string
	OutputLanguages   string
	SelectedPlatforms string
}

func (q *Queries) GetUserSettings(ctx context.Context, userID string) (GetUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i GetUserSettingsRow
	err := row.Scan(
		&i.KeywordsPerImage,
		&i.TitleStyle,
		&i.BlockedTerms,
		&i.OutputLanguages,
		&i.SelectedPlatforms,
	)
	return i, err
}

const insertGeneration = `-- name: InsertGeneration :one
insert into generations (
  user_id, filename, preview_key, title, description,
  keywords, category, provider, model, platform_id
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
returning id, filename, preview_key, title, description,
          keywords, category, provider, model, platform_id, created_at
`

type InsertGenerationParams struct {
	UserID      string
	Filename    string
	PreviewKey  *string
	Title       string
	Description string
	Keywords    []string
	Category    *string
	Provider    *string
	Model       *string
	PlatformID  *string
}

type InsertGenerationRow struct {
	ID          uuid.UUID
	Filename    string
	PreviewKey  *string
	Title       string
	Description string
	Keywords    []string
	Category    *string
	Provider    *string
	Model       *string
	PlatformID  *string
	CreatedAt   time.Time
}

func (q *Queries) InsertGeneration(ctx context.Context, arg InsertGenerationParams) (InsertGenerationRow, error) {
	row := q.db.QueryRow(ctx, insertGeneration,
		arg.UserID,
		arg.Filename,
		arg.PreviewKey,
		arg.Title,
		arg.Description,
		arg.Keywords,
		arg.Category,
		arg.Provider,
		arg.Model,
		arg.PlatformID,
	)
	var i InsertGenerationRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.PreviewKey,
		&i.Title,
		&i.Description,
		&i.Keywords,
		&i.Category,
		&i.Provider,
		&i.Model,
		&i.PlatformID,
		&i.CreatedAt,
	)
	return i, err
}

const listGenerations = `-- name: ListGenerations :many
select id, filename, preview_key, title, description,
       keywords, category, provider, model, platform_id, created_at
from generations
where user_id = $1
order by created_at desc
limit $2 offset $3
`

type ListGenerationsParams struct {
	UserID string
	Limit  int32
	Offset int32
}

type ListGenerationsRow struct {
	ID          uuid.UUID
	Filename    string
	PreviewKey  *string
	Title       string
	Description string
	Keywords    []string
	Category    *string
	Provider    *string
	Model       *string
	PlatformID  *string
	CreatedAt   time.Time
}

// ใหม่ไปเก่า ใช้ดัชนี generations_user_created_idx ตอบได้ทั้งกรองและเรียง
func (q *Queries) ListGenerations(ctx context.Context, arg ListGenerationsParams) ([]ListGenerationsRow, error) {
	rows, err := q.db.Query(ctx, listGenerations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenerationsRow
	for rows.Next() {
		var i ListGenerationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.PreviewKey,
			&i.Title,
			&i.Description,
			&i.Keywords,
			&i.Category,
			&i.Provider,
			&i.Model,
			&i.PlatformID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationsByPlatform = `-- name: ListGenerationsByPlatform :many
select id, filename, preview_key, title, description,
       keywords, category, provider, model, platform_id, created_at
from generations
where user_id = $1 and platform_id = $2
order by created_at desc
limit $3 offset $4
`

type ListGenerationsByPlatformParams struct {
	UserID     string
	PlatformID *string
	Limit      int32
	Offset     int32
}

type ListGenerationsByPlatformRow struct {
	ID          uuid.UUID
	Filename    string
	PreviewKey  *string
	Title       string
	Description string
	Keywords    []string
	Category    *string
	Provider    *string
	Model       *string
	PlatformID  *string
	CreatedAt   time.Time
}

// filter ตาม platform ใช้ดัชนี generations_platform_idx
func (q *Queries) ListGenerationsByPlatform(ctx context.Context, arg ListGenerationsByPlatformParams) ([]ListGenerationsByPlatformRow, error) {
	rows, err := q.db.Query(ctx, listGenerationsByPlatform,
		arg.UserID,
		arg.PlatformID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenerationsByPlatformRow
	for rows.Next() {
		var i ListGenerationsByPlatformRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.PreviewKey,
			&i.Title,
			&i.Description,
			&i.Keywords,
			&i.Category,
			&i.Provider,
			&i.Model,
			&i.PlatformID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPlatforms = `-- name: ListUserPlatforms :many
select distinct platform_id
from generations
where user_id = $1 and platform_id is not null
`

func (q *Queries) ListUserPlatforms(ctx context.Context, userID string) ([]*string, error) {
	rows, err := q.db.Query(ctx, listUserPlatforms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var platform_id *string
		if err := rows.Scan(&platform_id); err != nil {
			return nil, err
		}
		items = append(items, platform_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProfile = `-- name: UpsertProfile :one
insert into profiles (user_id, first_name, last_name, email, profile_url)
values ($1, $2, $3, $4, $5)
on conflict (user_id) do update set
  first_name  = excluded.first_name,
  last_name   = excluded.last_name,
  email       = excluded.email,
  profile_url = excluded.profile_url,
  updated_at  = now()
returning user_id, first_name, last_name, email, profile_url, user_type
`

type UpsertProfileParams struct {
	UserID     string
	FirstName  *string
	LastName   *string
	Email      *string
	ProfileUrl *string
}

type UpsertProfileRow struct {
	UserID     string
	FirstName  *string
	LastName   *string
	Email      *string
	ProfileUrl *string
	UserType   usertype.Type
}

// คัดลอกข้อมูลผู้ใช้จาก Clerk มาเก็บไว้ฝั่งเรา
// เพื่อให้ join กับตารางอื่นได้โดยไม่ต้องยิงไปถาม Clerk ทุกครั้ง
//
// user_type ไม่อยู่ในทั้งชุดที่ insert และชุดที่ update โดยตั้งใจ
// Clerk ไม่ใช่เจ้าของค่านี้ ตอนสร้างแถวใหม่จึงปล่อยให้เป็น default ของคอลัมน์
// และตอน sync โปรไฟล์ก็อ่านค่าเดิมกลับมาเฉย ๆ ไม่เขียนทับระดับที่ซื้อไว้
func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UpsertProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ProfileUrl,
	)
	var i UpsertProfileRow
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.ProfileUrl,
		&i.UserType,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :one
insert into user_settings (
  user_id, keywords_per_image, title_style, blocked_terms, output_languages, selected_platforms
) values ($1, $2, $3, $4, $5, $6)
on conflict (user_id) do update set
  keywords_per_image = excluded.keywords_per_image,
  title_style        = excluded.title_style,
  blocked_terms      = excluded.blocked_terms,
  output_languages   = excluded.output_languages,
  selected_platforms = excluded.selected_platforms,
  updated_at         = now()
returning keywords_per_image, title_style, blocked_terms, output_languages, selected_platforms
`

type UpsertUserSettingsParams struct {
	UserID            string
	KeywordsPerImage  int32
	TitleStyle        string
	BlockedTerms      string
	OutputLanguages   string
	SelectedPlatforms string
}

type UpsertUserSettingsRow struct {
	KeywordsPerImage  int32
	TitleStyle        string
	BlockedTerms      string
	OutputLanguages   string
	SelectedPlatforms string
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) (UpsertUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertUserSettings,
		arg.UserID,
		arg.KeywordsPerImage,
		arg.TitleStyle,
		arg.BlockedTerms,
		arg.OutputLanguages,
		arg.SelectedPlatforms,
	)
	var i UpsertUserSettingsRow
	err := row.Scan(
		&i.KeywordsPerImage,
		&i.TitleStyle,
		&i.BlockedTerms,
		&i.OutputLanguages,
		&i.SelectedPlatforms,
	)
	return i, err
}
